Migration to config MFD
AH-64D-Apache-Official-Project/AH-64D pull request #159
Opened 2022-01-25 23:04 UTC by mattysmith22

* Old MPD / UFD systems implemented

# UFD

* Removed old UFD
* Added config-based UFD
* Added ACRE support to UFD

# MPD

* Removed old MPD geometry
* Implemented following MPD pages
  * MENU
  * WPN
  * FUEL
  * FLT
  * WCA
  * TSD
  * FCR
  * ENG
  * ACE
  * DMS
  * DTU
* MPDs work on both screens
* Implemented A/C Button
* Implemented KU interaction

2022-08-23 00:54 UTC, Ollieollieolllie requested changes

2022-08-23 00:54 UTC, Ollieollieolllie commented on @AH-64D Apache Longbow/Addons/fza_ah64_ku/config.cpp
> +	{
needs updating to match control author list
required version needs updating
required addon needs updating

2022-08-23 00:54 UTC, Ollieollieolllie commented on @AH-64D Apache Longbow/Addons/fza_ah64_mpd/config.cpp
> +		author = "Franze, Nodunit, Sacha 'Voodooflies' Oropeza, Keplager & Community";
needs updating to match control author list
required version needs updating
required addon needs updating

2022-08-23 00:54 UTC, Ollieollieolllie commented on @AH-64D Apache Longbow/Addons/fza_ah64_mpd/functions/fn_drawMap.sqf
> -Function: fza_fnc_mpdUpdateMap
is thsi meant to be deleted

2022-08-23 00:54 UTC, Ollieollieolllie commented on @AH-64D Apache Longbow/Addons/fza_ah64_mpd/functions/fn_handleZoom.sqf
>  /* ----------------------------------------------------------------------------
Tsd range settings need hooking up

2022-08-23 00:54 UTC, Ollieollieolllie commented on @AH-64D Apache Longbow/Addons/fza_ah64_ufd/config.cpp
> +		author = "Franze, Nodunit, Sacha 'Voodooflies' Oropeza, Keplager & Community";
needs updating to match control author list
required version needs updating
required addon needs updating

2022-08-27 00:26 UTC, mattysmith22 commented
Review changes complete, merged to update

2022-08-27 00:27 UTC, Ollieollieolllie approved these changes
Great work

2022-08-27 00:27 UTC, merged