Ace Interaction & customization integration
AH-64D-Apache-Official-Project/AH-64D pull request #209
Opened 2022-10-24 22:58 UTC by Ollieollieolllie

Creating of Misc PBO to House Ace interact  & customization additions
Addition of Ace interact points -
- on the tail to set a five-figure tail number
- on the door handles to open the doors
- on the fire control radar to add and remove It
- on the body of the apache to install IAFS or 1200rnd Magazine

Creation of Empty objects
- Internal Auxilary fuel system 
- 1200 Magazine
- Fire control radar

Fix for Total fuel on fuel page fix
Fix for bus power to Cockpit lighting

2023-01-08 23:42 UTC, mattysmith22 requested changes

2023-01-09 00:22 UTC, Ollieollieolllie commented on @AH-64D Apache Longbow/Addons/fza_ah64_misc/$PBOPREFIX$
> +fza_ah64_misc
done

2023-01-22 21:07 UTC, mattysmith22 requested changes
Still have some outstanding questions from the previous review

2023-01-22 21:08 UTC, Ollieollieolllie commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/config/cfgVehicles.hpp
> +			useFlare = 1;
sorry, bad habit of fixing things while adding things
just made them more visible at day

2023-01-22 21:09 UTC, Ollieollieolllie commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/event/fn_eventInit.sqf
> +    if ((isLightOn [_heli,[0]]) && !_battBusOn) then {
sorry, bad habit of fixing things while adding things again
fixed the logic for flood lighting power

2023-03-14 21:37 UTC, mattysmith22 requested changes

2023-03-22 14:36 UTC, Ollieollieolllie commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/config/cfgVehicles.hpp
> +			flareSize = 15;
removed

2023-03-22 14:38 UTC, Ollieollieolllie commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/weapon/fn_weaponSwapM230Mag.sqf
> +_heli removeMagazineTurret ["fza_m230_1200", [0]];
yes, the addition of the different magazine causes it to have full ammo.
i could set it to 0 after changing

2023-03-22 14:40 UTC, Ollieollieolllie commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/weapon/fn_weaponSwapM230Mag.sqf
> +_heli removeMagazineTurret ["fza_m230_1200", [0]];
Gonna set it to 0

2023-04-03 00:57 UTC, BradMick approved these changes
Looks good to me. Nothing glaring stands out.

2023-04-03 00:59 UTC, merged