FCR page Icon Draw fix
AH-64D-Apache-Official-Project/AH-64D pull request #244
Opened 2023-04-27 12:14 UTC by BradMick

Adds a 'blank' icon to FzaIconTypes and corrects drawing logic on the FCR page.

2023-04-27 19:57 UTC, Ollieollieolllie submitted a review, later dismissed
Looks fine, tested it with no issuies

2023-04-29 13:29 UTC, mattysmith22 requested changes
If we don't want something to be shown, could we instead not add an icon to be rendered?

2023-04-30 22:18 UTC, mattysmith22 requested changes

2023-04-30 22:18 UTC, mattysmith22 commented on @AH-64D Apache Longbow/Addons/fza_ah64_mpd/functions/page/fn_pageFCRDraw.sqf
> +    if(_unitStatus !=  "BLANK") then {
Could `_unitStatus` ever be blank now? I think this if statement is now redundant

2023-04-30 22:18 UTC, mattysmith22 commented on @AH-64D Apache Longbow/Addons/fza_ah64_mpd/FzaIconTypes.hpp
> +    class FCR_FLYER_BLANK:FCR_ADU_BLANK {};
We no longer need these now right?

2023-04-30 22:21 UTC, BradMick commented on @AH-64D Apache Longbow/Addons/fza_ah64_mpd/FzaIconTypes.hpp
> +    class FCR_FLYER_BLANK:FCR_ADU_BLANK {};
Deleted...we shouldn't

2023-04-30 23:59 UTC, mattysmith22 approved these changes
Nice small PR, good job!

2023-05-01 00:05 UTC, merged