Apu Flameout & fuel consumption fix
AH-64D-Apache-Official-Project/AH-64D pull request #429
Opened 2023-07-16 21:48 UTC by Ollieollieolllie

2023-07-17 12:08 UTC, BradMick requested changes
You'll need to go to fn_apu.sqf and on line 53 change _apuFF to _apuFF_kgs, or else the APU will never actually burn any fuel

2023-07-17 15:45 UTC, Ollieollieolllie commented
Requested changes made

2023-07-17 21:31 UTC, BradMick requested changes

2023-07-17 21:31 UTC, BradMick commented on @AH-64D Apache Longbow/Addons/fza_ah64_sfmplus/functions/core/fn_coreUpdate.sqf
> -private _apuFF  = 0;
this needs to stay or else the value will never be reset to zero when the APU is off.

2023-07-18 21:56 UTC, mattysmith22 approved these changes

2023-07-18 22:17 UTC, BradMick approved these changes

2023-07-18 22:17 UTC, merged