M255 Deployment Smoke
AH-64D-Apache-Official-Project/AH-64D pull request #457
Opened 2023-08-02 01:03 UTC by Ollieollieolllie

This got lost somewhere along the way

2023-08-05 19:48 UTC, mattysmith22 requested changes

2023-08-05 19:48 UTC, mattysmith22 commented on @AH-64D Apache Longbow/Addons/fza_ah64_hydra/functions/fn_eventFired.sqf
> +    if (_counter > 3) exitWith {};
Has this been tested in multiplayer? My understanding was that `SubmunitionCreated` only ran on a single machine, and `drop` only has local effect

2023-08-05 19:48 UTC, mattysmith22 commented on @AH-64D Apache Longbow/Addons/fza_ah64_hydra/functions/fn_eventFired.sqf
> +Function: fza_fnc_eventFired
This looks incorrect?

2023-08-05 19:48 UTC, mattysmith22 commented on @AH-64D Apache Longbow/Addons/fza_ah64_hydra/functions/fn_eventFired.sqf
> +    Submunition creation event handler
The description should help explain what this function does

2023-08-05 19:48 UTC, mattysmith22 commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/XEH_preInit.sqf
> +fza_ah64_salvofired = 1;
I don't think this is the correct way. To me it looks like the fired event handler order is incorrect. Maybe try in `extendedEventHandlers.hpp` changing the fired eventhandler from

```cpp
firedBIS = "_this call fza_fnc_eventFired; _this call fza_fnc_fxMuzzle; fza_ah64_salvofired = fza_ah64_salvofired + 1;";
```

to

```cpp
firedBIS = " _this call fza_fnc_fxMuzzle; fza_ah64_salvofired = fza_ah64_salvofired + 1;_this call fza_fnc_eventFired;";
```

2023-08-05 19:48 UTC, mattysmith22 commented on @AH-64D Apache Longbow/Addons/fza_ah64_hydra/functions/fn_eventFired.sqf
> +if (typeOf _submunitionProjectile == "fza_flec_cluster") then {
Could you early-exit here?

```sqf
if (typeOf _submunitionProjectile != "fza_flex_cluster") exitWith {}
```

2023-08-27 16:46 UTC, BradMick approved these changes
Good to go

2023-09-04 18:28 UTC, mattysmith22 approved these changes

2023-09-04 18:29 UTC, merged