Tail number Eden control 7 to 5 Characters
AH-64D-Apache-Official-Project/AH-64D pull request #465
Opened 2023-08-13 22:30 UTC by Ollieollieolllie

2023-08-20 18:06 UTC, mattysmith22 requested changes

2023-08-20 18:06 UTC, mattysmith22 commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/fn_setTailNumber.sqf
> +//_heli setObjectTextureGlobal ["tailDigit_06", _validChars getOrDefault [_char06, ""]];
Why comment rather than remove?

If we need them, we can re-add

2023-08-26 20:51 UTC, BradMick approved these changes

2023-08-26 22:18 UTC, mattysmith22 approved these changes

2023-08-26 22:18 UTC, merged