System connections
AH-64D-Apache-Official-Project/AH-64D pull request #569
Opened 2024-06-17 20:59 UTC by Ollieollieolllie

2024-10-25 18:36 UTC, mattysmith22 requested changes
One small change! Other than that looks good

2024-10-25 18:36 UTC, mattysmith22 commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/config/cfgVehicles/turrets.hpp
> +        weapons[] = {"fza_ma_safe", "Laserdesignator_mounted","fza_m230", "fza_cannon_limit", "fza_gun_inhibit", "fza_hydra_limit", "fza_Pylon_inhibit"};
Capitalisation of pylon is wrong

2024-10-25 19:38 UTC, Ollieollieolllie commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/config/cfgVehicles/turrets.hpp
> +        weapons[] = {"fza_ma_safe", "Laserdesignator_mounted","fza_m230", "fza_cannon_limit", "fza_gun_inhibit", "fza_hydra_limit", "fza_Pylon_inhibit"};
resolved

2024-10-26 19:58 UTC, mattysmith22 requested changes

2024-10-26 20:01 UTC, mattysmith22 approved these changes

2024-10-26 20:01 UTC, merged